---
- name: test play
  hosts: localhost
  tasks:
    - name: test
      debug:
        msg: "{{ item }}"
      loop:
        - "Hello World 1"
        - "Hello World 2"
        - "Hello World 3"
        - "Hello World 4"
        - "Hello World 5"

